# Generated by Django 4.1.1 on 2022-11-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicinfo",
            name="gender",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basicinfo",
            name="profile_picture",
            field=models.ImageField(default=None, upload_to="profile_picture"),
            preserve_default=False,
        ),
    ]
