# Generated by Django 4.1.1 on 2022-11-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_remove_basicinfo_profile_picture_profilepicture"),
    ]

    operations = [
        migrations.RemoveField(model_name="profilepicture", name="id",),
        migrations.AlterField(
            model_name="profilepicture",
            name="basic_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name="profile_picture",
                serialize=False,
                to="survey.basicinfo",
            ),
        ),
    ]
